FileVersion = 1
Dependencies = {corlib = "*", DirectX = "*"}

[Project]
Name = "SimpleAudioPlayback"
StartupObject = "SimpleAudioPlayback.Program"

[Configs.Debug.Win64]
PreBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/content\", \"$(BuildDir)\")"]
