FileVersion = 1
Dependencies = {corlib = "*", DirectX = "*"}

[Project]
Name = "Example"
TargetType = "BeefGUIApplication"
StartupObject = "Example.Program"

[Configs.Debug.Win64]
PreBuildCmds = ["ROBOCOPY \"$(ProjectDir)/content\" \"$(BuildDir)/content\" /S /XO"]
