FileVersion = 1
Dependencies = {corlib = "*", DirectX = "*"}

[Project]
Name = "SimpleTriangleExample"
TargetType = "BeefGUIApplication"
StartupObject = "SimpleTriangleExample.Program"

[Configs.Debug.Win64]
PreBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/content\", \"$(BuildDir)\")"]
