FileVersion = 1
Dependencies = {corlib = "*", DirectX = "*"}

[Project]
Name = "SimpleTriangleExample"
TargetType = "BeefGUIApplication"
StartupObject = "SimpleTriangleExample.Program"
DefaultNamespace = "SimpleTriangleExample"

[Configs.Debug.Win64]
PreBuildCmds = ["ROBOCOPY \"$(ProjectDir)/content\" \"$(BuildDir)/content\" /S /XO"]
