FileVersion = 1
Dependencies = {corlib = "*", DirectX = "*"}

[Project]
Name = "CallbackExample"
StartupObject = "CallbackExample.Program"

[Configs.Debug.Win64]
PreBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/content\", \"$(BuildDir)\")"]
